name: Download news data

on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch:
    
jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download news data
      run: |
        node scrawl.js
    - name: Add and commit
      uses: EndBug/add-and-commit@v4.2.1

